"""
Dialogue Tree — Tiered Activation Engine
RRT AIdvocAIte — Protective Layer of the Solidarity Framework

Manages user journeys through the Stage 0–5 activation sequence.
Routes stage transitions through the TOI/OTOI middleware and
FusionEngine to ensure every response is persona-blended and TOI-compliant.
"""

import logging
from dataclasses import dataclass, field
from typing import Optional, Dict, Any, List
from datetime import datetime

from toi.toi_models import TOIConfig
from toi.otoi_middleware import OTOIMiddleware
from personas.fusion_engine import (
    FusionEngine,
    EngineContext,
    DistressInput,
    BlendedResponse,
    PersonaWeights,
)
from .stages import ActivationStage, StageConfig, StageOption, STAGE_CONFIGS

logger = logging.getLogger(__name__)

_DISTRESS_INPUT_MAP: Dict[str, DistressInput] = {
    "everything_hurts_meltdown": DistressInput.EVERYTHING_HURTS_MELTDOWN,
    "cant_do_basic_tasks": DistressInput.CANT_DO_BASIC_TASKS,
    "cant_stop_self_blame": DistressInput.CANT_STOP_SELF_BLAME,
    "stuck_in_hyperfocus_loop": DistressInput.STUCK_IN_HYPERFOCUS_LOOP,
    "dont_know_shut_down": DistressInput.DONT_KNOW_SHUT_DOWN,
}


@dataclass
class StageTransition:
    """Records a single stage transition in the dialogue history."""
    from_stage: ActivationStage
    to_stage: ActivationStage
    option_key: str
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class DialogueState:
    """
    The full runtime state of an active dialogue session.

    Tracks the current stage, the active distress input, persona weights,
    and the complete transition history.
    """
    current_stage: ActivationStage = ActivationStage.STAGE_0_PASSIVE
    current_distress_input: Optional[DistressInput] = None
    current_persona_weights: Optional[PersonaWeights] = None
    last_blended_response: Optional[BlendedResponse] = None
    silent_mode_active: bool = False
    transition_history: List[StageTransition] = field(default_factory=list)
    session_context: Dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=datetime.now)
    last_updated: datetime = field(default_factory=datetime.now)

    def record_transition(self, transition: StageTransition):
        self.transition_history.append(transition)
        self.last_updated = datetime.now()


class DialogueTree:
    """
    Tiered Activation Dialogue Tree.

    Orchestrates the user journey through Stages 0–5, routing each
    transition through the TOI/OTOI middleware and FusionEngine.

    Key principles:
    - Agency First: Never advance past Stage 1 without explicit consent.
    - No Forced Progression: Users can stay in any stage indefinitely.
    - TOI Compliance: Every response is filtered through OTOI middleware.
    - Local-First: No external calls required for core logic.
    """

    def __init__(
        self,
        toi_config: TOIConfig,
        otoi_middleware: OTOIMiddleware,
        fusion_engine: Optional[FusionEngine] = None,
        crisis_level_score: float = 0.0,
    ):
        self.toi_config = toi_config
        self.otoi = otoi_middleware
        self.fusion_engine = fusion_engine or FusionEngine()
        self.crisis_level_score = crisis_level_score
        self.state = DialogueState()

        if toi_config.silent_mode_preferred:
            self.state.silent_mode_active = True

    # -------------------------------------------------------------------------
    # Primary interaction method
    # -------------------------------------------------------------------------

    def get_current_prompt(self) -> str:
        """Return the prompt for the current stage."""
        config = STAGE_CONFIGS.get(self.state.current_stage)
        if config is None:
            return ""

        # Stage 3 prompt is dynamically generated by FusionEngine
        if self.state.current_stage == ActivationStage.STAGE_3_INTERVENTION:
            return self._get_intervention_prompt()

        return config.prompt

    def get_current_options(self) -> List[StageOption]:
        """Return the selectable options for the current stage."""
        config = STAGE_CONFIGS.get(self.state.current_stage)
        return config.options if config else []

    def process_option_selection(
        self,
        option_key: str,
        free_text: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Process a user's option selection and advance the dialogue.

        This is the primary interaction handler. It:
        1. Validates the option against the current stage.
        2. Applies stage transition metadata (consent, silent mode, distress input).
        3. Advances to the next stage.
        4. Returns the new stage prompt and options.

        Args:
            option_key: The key of the selected option.
            free_text: Optional free-form user message (used for distress inference).

        Returns:
            Dict with new stage info, prompt, options, and any blended response.
        """
        current_config = STAGE_CONFIGS.get(self.state.current_stage)
        if current_config is None:
            return self._error_response("Invalid stage state.")

        # Find the selected option
        selected = next(
            (opt for opt in current_config.options if opt.key == option_key),
            None,
        )
        if selected is None:
            return self._error_response(f"Unknown option '{option_key}' at stage {self.state.current_stage.name}.")

        # Apply transition metadata
        self._apply_transition_metadata(selected.metadata, free_text)

        # Record the transition
        next_stage = selected.next_stage or self.state.current_stage
        transition = StageTransition(
            from_stage=self.state.current_stage,
            to_stage=next_stage,
            option_key=option_key,
            metadata=selected.metadata,
        )
        self.state.record_transition(transition)

        # Advance to next stage
        prev_stage = self.state.current_stage
        self.state.current_stage = next_stage

        logger.info(
            "Dialogue: %s → %s (option=%s)",
            prev_stage.name, next_stage.name, option_key,
        )

        return self._build_stage_response()

    def process_free_text(self, text: str) -> Dict[str, Any]:
        """
        Process a free-text user message at any stage.

        Infers distress input from text if not in a stage with explicit options,
        then generates a FusionEngine response.

        Args:
            text: Free-form user message.

        Returns:
            FusionEngine blended response and updated stage info.
        """
        # Check if consent is needed first
        if not self.otoi.check_consent() and self.state.current_stage != ActivationStage.STAGE_1_ENTRY:
            self.state.current_stage = ActivationStage.STAGE_1_ENTRY
            return self._build_stage_response()

        # Infer distress input from text
        inferred = self.fusion_engine.infer_distress_input_from_text(text)
        if inferred:
            self.state.current_distress_input = inferred
            logger.debug("Inferred distress input from free text: %s", inferred.value)

        # If we're in Stage 3, generate a fresh intervention
        if self.state.current_stage == ActivationStage.STAGE_3_INTERVENTION:
            self._refresh_intervention(free_text=text)

        return self._build_stage_response()

    # -------------------------------------------------------------------------
    # Internal helpers
    # -------------------------------------------------------------------------

    def _apply_transition_metadata(
        self, metadata: Dict[str, Any], free_text: Optional[str]
    ):
        """Apply metadata from a stage option to the dialogue state."""
        if metadata.get("grants_consent"):
            self.otoi.grant_consent()

        if metadata.get("activate_silent_mode"):
            self.state.silent_mode_active = True
            self.otoi.activate_silent_mode()

        distress_key = metadata.get("distress_input")
        if distress_key and distress_key in _DISTRESS_INPUT_MAP:
            self.state.current_distress_input = _DISTRESS_INPUT_MAP[distress_key]
        elif distress_key is None and free_text:
            # Try to infer from free text
            inferred = self.fusion_engine.infer_distress_input_from_text(free_text)
            if inferred:
                self.state.current_distress_input = inferred

        if metadata.get("escalate"):
            self.state.session_context["escalation_requested"] = True

    def _get_intervention_prompt(self) -> str:
        """Generate the Stage 3 intervention prompt via FusionEngine."""
        context = EngineContext(
            distress_input=self.state.current_distress_input,
            crisis_level_score=self.crisis_level_score,
            silent_mode_active=self.state.silent_mode_active,
            session_context=self.state.session_context,
        )
        weights = self.fusion_engine.compute_weights(context, self.toi_config)
        blended = self.fusion_engine.blend_response(context, weights, self.toi_config)

        self.state.current_persona_weights = weights
        self.state.last_blended_response = blended

        # Apply OTOI filter
        allowed_personas = self.otoi.validate_persona_routing(blended.active_personas)
        filtered_response = self.otoi.filter_response(
            blended.template_response, blended.dominant_persona
        )

        return filtered_response

    def _refresh_intervention(self, free_text: str = ""):
        """Re-run the FusionEngine with updated context for continued Stage 3 presence."""
        context = EngineContext(
            user_message=free_text,
            distress_input=self.state.current_distress_input,
            crisis_level_score=self.crisis_level_score,
            silent_mode_active=self.state.silent_mode_active,
            session_context=self.state.session_context,
        )
        weights = self.fusion_engine.compute_weights(context, self.toi_config)
        blended = self.fusion_engine.blend_response(context, weights, self.toi_config)
        self.state.current_persona_weights = weights
        self.state.last_blended_response = blended

    def _build_stage_response(self) -> Dict[str, Any]:
        """Build the response dict for the current stage."""
        config = STAGE_CONFIGS.get(self.state.current_stage)
        prompt = self.get_current_prompt()
        options = self.get_current_options()

        response = {
            "stage": self.state.current_stage.name,
            "stage_number": self.state.current_stage.value,
            "prompt": prompt,
            "options": [
                {"key": opt.key, "display_text": opt.display_text}
                for opt in options
            ],
            "silent_mode_active": self.state.silent_mode_active,
            "consent_given": self.otoi.check_consent(),
        }

        if self.state.last_blended_response:
            response["persona_context"] = {
                "dominant_persona": self.state.last_blended_response.dominant_persona,
                "active_personas": self.state.last_blended_response.active_personas,
                "weights": self.state.current_persona_weights.as_dict()
                    if self.state.current_persona_weights else None,
                "system_prompt": self.state.last_blended_response.system_prompt,
                "silent_mode_triggered": self.state.last_blended_response.silent_mode_triggered,
            }

        return response

    def _error_response(self, message: str) -> Dict[str, Any]:
        logger.error("DialogueTree error: %s", message)
        return {
            "stage": self.state.current_stage.name,
            "error": message,
            "prompt": STAGE_CONFIGS[self.state.current_stage].prompt,
            "options": [
                {"key": opt.key, "display_text": opt.display_text}
                for opt in self.get_current_options()
            ],
        }

    def get_session_summary(self) -> Dict[str, Any]:
        """Return a summary of the dialogue session."""
        return {
            "current_stage": self.state.current_stage.name,
            "current_distress_input": (
                self.state.current_distress_input.value
                if self.state.current_distress_input else None
            ),
            "silent_mode_active": self.state.silent_mode_active,
            "consent_given": self.otoi.check_consent(),
            "transitions": len(self.state.transition_history),
            "persona_weights": (
                self.state.current_persona_weights.as_dict()
                if self.state.current_persona_weights else None
            ),
            "otoi_summary": self.otoi.get_session_summary(),
        }
